server:
  port: 8082

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: demo
  resource: springboot-keycloak
  public-client: true
  bearer-only: true


spring:

  datasource:

    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jurusan
    username: postgres
    password: pro5
    hikari:
      initialization-fail-timeout: 0

  jpa:

    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
